# Generated by Django 3.1.6 on 2021-06-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bagahe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Address2', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=50)),
                ('Number2', models.CharField(max_length=50)),
                ('payment', models.CharField(choices=[('pay1', 'Annual'), ('pay2', 'Semi-Annual'), ('pay3', 'Quarterly'), ('pay4', 'Monthly')], default='pay1', max_length=50)),
                ('atm', models.CharField(choices=[('card1', 'atm1'), ('card2', 'atm2'), ('card3', 'atm3'), ('card4', 'atm4')], default='card1', max_length=15)),
                ('CVV', models.CharField(max_length=50)),
                ('CARD_NUMBER', models.CharField(max_length=50)),
                ('buwan', models.CharField(choices=[('month1', 'January'), ('month2', 'February'), ('month3', 'March'), ('month4', 'April'), ('month5', 'May'), ('month6', 'June'), ('month7', 'July'), ('month8', 'August'), ('month9', 'September'), ('month10', 'October'), ('month11', 'November'), ('month12', 'December')], default='month1', max_length=15)),
                ('taon', models.CharField(choices=[('year1', '2021'), ('year2', '2022'), ('year3', '2023'), ('year4', '2024'), ('year5', '2025')], default='year1', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Bayad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulaklak', models.CharField(choices=[('flow1', 'All white Standing sympathy'), ('flow2', 'Always remember (WHITE STANDING)'), ('flow3', 'Angelic All White Wreath'), ('flow4', 'Care and Compassion Spray'), ('flow5', 'Classic all Whites Standing Spray'), ('flow6', 'From your loving family'), ('flow7', 'Funeral White Basket')], default='flow1', max_length=15)),
                ('inch', models.CharField(choices=[('sukat1', 'Regular'), ('sukat2', '10 inches'), ('sukat3', '15 inches'), ('sukat4', '20 inches'), ('sukat5', '25 inches'), ('sukat6', '30 inches')], default='flow1', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=50)),
                ('Total', models.CharField(max_length=50)),
                ('urns', models.CharField(choices=[('Urns1', 'Individual Cremation Urns'), ('Urns2', 'Companion Cremation Urns'), ('Urns3', 'Keepsake Cremation Urns'), ('Urns4', '3D Artisan Portrait Cremation Urns'), ('Urns5', 'Child and Infant Cremation Urns'), ('Urns6', 'Pet Cremation Urns')], default='Urns1', max_length=15)),
                ('inches', models.CharField(choices=[('Size1', 'Regular size'), ('Size2', '15 cubic inches'), ('Size3', '100 cubic inches'), ('Size4', '200 cubic inches'), ('Size5', '220 cubic inches'), ('Size6', '250 cubic inches'), ('Size7', '300 cubic inches')], default='Size1', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('male', 'male1'), ('female', 'female1')], max_length=50)),
                ('Contact', models.IntegerField()),
                ('Address', models.CharField(max_length=50)),
                ('birthday', models.DateField(null=True)),
                ('relation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casket', models.CharField(choices=[('Item1', 'Wooden Casket'), ('Item2', 'Metal Casket'), ('Item3', 'Imported Casket')], default='Item1', max_length=15)),
                ('Quantity', models.IntegerField()),
                ('size', models.CharField(choices=[('size1', 'Length: 78 inches Width: 23 inches'), ('size2', 'Length: 75 inches Width: 22 inches'), ('size3', 'Length: 83 inches Width: 28 inches'), ('size4', 'Length: 85 inches Width: 38 inches'), ('size5', 'Length: 60 inches Width: 11 inches')], default='size1', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField(max_length=100, null=True)),
                ('User', models.ManyToManyField(to='ctlist.Form')),
            ],
        ),
        migrations.CreateModel(
            name='Starling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(choices=[('star5', '5'), ('star4', '4'), ('star3', '3'), ('star2', '2'), ('star1', '1')], default='none', max_length=20)),
                ('User', models.ManyToManyField(to='ctlist.Form')),
            ],
        ),
    ]
