# Generated by Django 3.2.3 on 2021-05-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField(max_length=100, null=True)),
                ('User', models.ManyToManyField(to='ctlist.Form')),
            ],
        ),
        migrations.CreateModel(
            name='Starling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(choices=[('star5', '5'), ('star4', '4'), ('star3', '3'), ('star2', '2'), ('star1', '1')], default='none', max_length=20)),
                ('User', models.ManyToManyField(to='ctlist.Form')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(null=True)),
                ('Quantity1', models.IntegerField(null=True)),
                ('Quantity2', models.IntegerField(null=True)),
                ('Quantity3', models.IntegerField(null=True)),
                ('Quantity4', models.IntegerField(null=True)),
                ('Quantity5', models.IntegerField(null=True)),
                ('Total', models.IntegerField(null=True)),
                ('User', models.ManyToManyField(to='ctlist.Form')),
            ],
        ),
        migrations.CreateModel(
            name='Bayad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment', models.CharField(choices=[('gcash1', 'gcash'), ('paymaya2', 'paymaya'), ('diskartech3', 'diskartech'), ('cash4', 'cashondelivery')], default='none', max_length=20)),
                ('User', models.ManyToManyField(to='ctlist.Form')),
            ],
        ),
        migrations.CreateModel(
            name='Bagahe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment', models.CharField(choices=[('lalamove1', 'lalamove'), ('jandt2', 'jandt'), ('jrs3', 'jrs'), ('mrspeed4', 'mrspeed')], default='none', max_length=20)),
                ('User', models.ManyToManyField(to='ctlist.Form')),
            ],
        ),
    ]
