# Generated by Django 3.1.6 on 2021-06-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagahe',
            name='select',
            field=models.CharField(choices=[('male', 'male1'), ('female', 'female1')], default='none', max_length=50),
        ),
    ]
