# Generated by Django 3.1.6 on 2021-04-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='Essential',
            field=models.CharField(choices=[('Gloves1', 'Gloves'), ('Alcohol2', 'Alcohol'), ('Facemask3', 'Facemask'), ('Faceshield4', 'Faceshield'), ('SetofPPE5', 'Set of PPE'), ('HandSanitizer6', 'Hand Sanitizer')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='Name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='Payment',
            field=models.CharField(choices=[('CashonDelivery1', 'Cash on Delivery'), ('OnlinePayment2', 'Online Payment'), ('Meetup3', 'Meet up')], default='none', max_length=20),
        ),
    ]
