# Generated by Django 3.1.6 on 2021-06-22 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctlist', '0004_auto_20210622_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starling',
            name='User',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
    ]
