# Generated by Django 3.1.6 on 2021-06-23 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctlist', '0005_auto_20210622_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='Gantangproduct2',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='Product_Category2',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='Radio',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='price2',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='quantity2',
        ),
    ]
