# Generated by Django 3.1.6 on 2021-06-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctlist', '0009_auto_20210623_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagahe',
            name='mode',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
