# Generated by Django 3.1.6 on 2021-06-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctlist', '0010_bagahe_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bagahe',
            old_name='CVV',
            new_name='cvv',
        ),
    ]
