# Generated by Django 3.1.6 on 2021-06-23 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctlist', '0011_auto_20210623_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='quantity',
            new_name='Quantity',
        ),
    ]
