# Generated by Django 3.1.6 on 2021-06-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctlist', '0012_auto_20210623_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagahe',
            name='payment',
            field=models.CharField(choices=[('Annual', 'Annual'), ('Semi-Annual', 'Semi-Annual'), ('Quarterly', 'Quarterly'), ('Monthly', 'Monthly')], default='pay1', max_length=50),
        ),
    ]
