# Generated by Django 3.1.6 on 2021-06-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctlist', '0013_auto_20210623_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagahe',
            name='payment',
            field=models.CharField(choices=[('Annual', 'pay1'), ('Semi-Annual', 'pay2'), ('Quarterly', 'pay3'), ('Monthly', 'pay4')], default='pay1', max_length=50),
        ),
    ]
