# Generated by Django 3.1.6 on 2021-06-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctlist', '0014_auto_20210623_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagahe',
            name='Month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='month1', max_length=50),
        ),
        migrations.AlterField(
            model_name='bagahe',
            name='Year',
            field=models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default='year1', max_length=50),
        ),
        migrations.AlterField(
            model_name='bagahe',
            name='atm',
            field=models.CharField(choices=[('Savings accounts', 'Savings accounts'), ('Checking accounts', 'Checking accounts'), ('Salary account', 'Salary account'), ('Walk-in', 'Walk in')], default='card1', max_length=50),
        ),
        migrations.AlterField(
            model_name='bagahe',
            name='payment',
            field=models.CharField(choices=[('Annual', 'Annual'), ('Semi-Annual', 'Semi-Annual'), ('Quarterly', 'Quarterly'), ('Monthly', 'Monthly')], default='pay1', max_length=50),
        ),
    ]
